### ISSUE TITLE
参考文献设置问题

### ISSUE THREAD

**Issue by joebling** [yihui/r-ninja#15]
在18-renferences.Rmd
`r if (knitr:::is_html_output()) '# 参考文献 {#reference .unnumbered}'`

```{r include=FALSE}
knitr::write_bib(
  .packages(),
  'packages.bib'
)
```
我们可以看到packages.bib被生成, 
内容如下
@Manual{R-base,
  title = {R: A Language and Environment for Statistical Computing},
  author = {{R Core Team}},
  organization = {R Foundation for Statistical Computing},
  address = {Vienna, Austria},
  year = {2016},
  url = {https://www.R-project.org/},
}
@Manual{R-rmini,
  title = {rmini: A Minimal R Package as an Example of Writing R Packages},
  author = {Yihui Xie},
  year = {2014},
  note = {R package version 0.0.4},
  url = {https://github.com/yihui/rmini},
}

但是生成的html中的参考文献只有
R Core Team. 2016. R: A Language and Environment for Statistical Computing. Vienna, Austria: R Foundation for Statistical Computing. https://www.R-project.org/.

为什么对不上？

是我哪里错了么？

@yihui 

thanks

**Comment by yihui** [comment]
你没错，是在下错了，在下没有真的引用第二个条目，即：文中没有 `@R-rmini`
