### ISSUE TITLE
bookdown对于pdf中文的支持问题？

### ISSUE THREAD

**Issue by weijy026a** [yihui/r-ninja#17]
我尝试使用bookdown来写中文文章（使用xelatex编译），发现bookdown对于作者名称、文章标题，章节的中文的支持都有问题，可以提供一个模板么？多谢！

**Comment by yihui** [comment]
好问题，这个我暂时还没有研究，不过应该不会很困难。你可以研究一下我在 rticles 包中的 ctex 模板。

**Comment by weijy026a** [comment]
我对于latex只是简单会用，不太熟，希望能够得到大神的帮助，我把问题已发你的邮箱，多谢！

**Comment by yihui** [comment]
暂时木有时间 😭

**Comment by yihui** [comment]
我还没来得及看你的例子，但我昨晚自己突击了一个简单的例子：https://github.com/yihui/bookdown-chinese 不是很酷，但好歹中文 PDF 可以编出来了。

**Comment by weijy026a** [comment]
多谢！

**Comment by XiangyunHuang** [comment]
我发现使用 `rticles::ctex` 也是可以达到同样目的的

```ymal
title: "在R Markdown文档中使用中文"
author:
  - 谢益辉
  - 邱怡轩
  - 于淼
documentclass: ctexbook
output:
  rticles::ctex:
    fig_caption: yes
    citation_package: natbib
    number_sections: yes
    toc: yes
    toc_depth: 4
    pandoc_args: "--top-level-division=chapter"
lot: true
lof: true    
classoption: "hyperref,"
bibliography: [book.bib, packages.bib]
biblio-style: apalike
biblio-title: 参考文献
```

![rticles-ctexbook](https://user-images.githubusercontent.com/12031874/34816543-37cefbbe-f6f0-11e7-8528-e9d310b00da1.png)

**Comment by xiaoyao177147** [comment]
李东风老师在[R语言教程](http://www.math.pku.edu.cn/teachers/lidf/docs/Rbook/html/_Rbook/bookdown.html#bookdown-compile)  22.12一节提到：为了能够生成中文的PDF，不要指定doclass为ctexbook， 而是指定为book，然后在preamble.tex中引入ctex包。请问ctexbook的缺陷是什么，我现在准备采用bookdownplus的pku_zh模板来写毕业论文，而该模板基于ctexbook。

**Comment by XiangyunHuang** [comment]
@xiaoyao177147 可以指定 ctexbook 的，比如 @yihui 的 https://github.com/yihui/bookdown-chinese

**Comment by XiangyunHuang** [comment]
@yihui 感觉这个issues可以关闭了

**Comment by yihui** [comment]
好，谢谢。
