### ISSUE TITLE
在macOS下编译的两个问题

### ISSUE THREAD

**Issue by hanwentao** [yihui/r-ninja#19]
刚开始用bookdown，macOS 10.12.3，RStudio 1.0.138，遇到两个问题：

1. Build Book时出现如下错误信息：

```
Quitting from lines 399-404 (r-ninja.Rmd) 
Error in file(con, "r") : cannot open the connection
Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> readLines -> file
Execution halted

Exited with status 1.
```

发现出问题的行是402行`xie = readLines('http://yihui.name') # 我的主页`，在命令行下访问 https://yihui.name 成功，但是http会出错。

2. 修改之后再点Build Book，错误依旧，发现修改被重置了……

**Comment by yihui** [comment]
1是因为我后来启用了 https，现在已经修正；2是因为 r-ninja.Rmd 是个临时文件，它是所有 Rmd 合并生成的文件，编译成功的话会被删掉，失败的话你可以拿它查错，但不能修改。
