### ISSUE TITLE
两个问题

### ISSUE THREAD

**Issue by nanxstats** [yihui/r-ninja#4]
@yihui github不支持对md文件的按行评论？连md文件的按行引用也木有？
- setup一章中 `language = en` 的 `en` 似乎用大写的 `EN` 更准确?
- setup一章中 「用自定义方式安装」的写作策略需调整 2.15.0抛弃了多数安装选项 基本不可定制了 截图也需要更新

**Comment by gitzhuoer** [comment]
setup一章中 「用自定义方式安装」的写作策略需调整, 3.4.1又可以选择了不安装消息翻译文件了 @yihui 

新的截图如下
http://i706.photobucket.com/albums/ww62/capstat/R_zps2im1o0mi.png

顺便问一下，你在统计之都推荐的推荐图片上传网站（1）http://imgur.com和（2）http://photobucket.com好像都不能注册账号了。imgur貌似满了，photobucket好像屏蔽代理（然而又用到了Google的人机验证，强行封杀大陆用户啊:cry:）
